//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoPhan
    {
        public int MaBoPhan { get; set; }
        public string TenBoPhan { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
    }
}
