//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int MaChamCong { get; set; }
        public Nullable<System.DateTime> NgayChamCong { get; set; }
        public Nullable<System.TimeSpan> GioVao { get; set; }
        public Nullable<System.TimeSpan> GioRa { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string KetQuaChamCong { get; set; }
        public string MaLoaiCa { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
