//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKhoaDaoTao
    {
        public int MaNhanVien { get; set; }
        public int MaDaoTao { get; set; }
        public Nullable<int> ThoiGianDuKien { get; set; }
        public string DanhGiaKhoa { get; set; }
    
        public virtual DaoTao DaoTao { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
