//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDuAn
    {
        public int MaNhanVien { get; set; }
        public int MaDuAn { get; set; }
        public Nullable<System.DateTime> ThoiHanDuAn { get; set; }
        public string DanhGia { get; set; }
        public string VaiTro { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
