//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKT_KL
    {
        public int MaNhanVien { get; set; }
        public int MaSuKien { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<decimal> TienThuongPhat { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual KT_KL KT_KL { get; set; }
    }
}
