//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_KL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KT_KL()
        {
            this.ChiTietKT_KL = new HashSet<ChiTietKT_KL>();
        }
    
        public int MaSuKien { get; set; }
        public string LoaiSuKien { get; set; }
        public Nullable<System.DateTime> NgayDienRa { get; set; }
        public string LyDo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKT_KL> ChiTietKT_KL { get; set; }
    }
}
