//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuHoatDong
    {
        public int MaHoatDong { get; set; }
        public string LoaiHoatDong { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string TenDangNhap { get; set; }
        public string GhiChu { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
