//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_DieuChuyen
    {
        public int SoDC { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
        public Nullable<int> MaPhongBan2 { get; set; }
        public string LyDoDC { get; set; }
        public string GhiChuDC { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaChucVu2 { get; set; }
    }
}
