//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuLuong
    {
        public int MaPhieuLuong { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgayTinhLuong { get; set; }
        public Nullable<decimal> LuongCoBan { get; set; }
        public Nullable<decimal> TangCa { get; set; }
        public Nullable<decimal> PhuCap { get; set; }
        public Nullable<decimal> UngLuong { get; set; }
        public Nullable<double> NgayCong { get; set; }
        public Nullable<decimal> KTKL { get; set; }
        public Nullable<decimal> TienBaoHiem { get; set; }
        public Nullable<decimal> LuongNhanDuoc { get; set; }
        public string TrangThaiTraLuong { get; set; }
        public Nullable<int> MaKyCong { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
