//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TangCa
    {
        public int MaNhanVien { get; set; }
        public string MaLoaiCa { get; set; }
        public string HoTen { get; set; }
        public string TenLoaiCa { get; set; }
        public Nullable<decimal> HeSo { get; set; }
        public Nullable<decimal> SoGio { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string GhiChu { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual LoaiCa LoaiCa { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
